---
- hosts: server01
  gather_facts: false
  tasks:
    - name: Create ServiceNow ticket to resolve issue
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        short_description: "Unable to ping {{ inventory_hostname }}"
        impact: medium
        urgency: high

