---
- hosts: server01
  gather_facts: true
  tasks:
  - name: Run apt-get update
    ansible.builtin.apt:
      update_cache: yes

  - name: Install apache
    ansible.builtin.apt:
      name: apache2
      state: latest

  - name: Start apache service
    ansible.builtin.service:
      name: apache2
      state: started

  - name: Copy welcome page artifacts
    ansible.builtin.copy:
      content: "{{ item }}"
      dest: "/var/www/html/{{ item }}"
    loop:
      - awx-spud.svg
      - index.html

  - name: Create test welcome page
    ansible.builtin.copy:
      content: "{{ lookup('template', 'index.html') }}"
      dest: "/var/www/html/index.html"

