---
- hosts: server01
  gather_facts: true
  tasks:
  - name: Run apt-get update
    ansible.builtin.apt:
      update_cache: yes

  - name: Install apache
    ansible.builtin.apt:
      name: apache2
      state: latest

  - name: Copy welcome page artifacts
    ansible.builtin.template:
      src: "{{ item }}"
      dest: "/var/www/html/{{ item }}"
    loop:
      - awx-spud.svg
      - index.html

  - name: Start Apache service
    ansible.builtin.service:
      state: started
      name: apache2

