---
- hosts: server01
  gather_facts: true
  tasks:
  - name: Run apt-get update
    ansible.builtin.apt:
      update_cache: yes

  - name: Install apache
    ansible.builtin.apt:
      name: apache2
      state: latest

  - name: Start apache service
    ansible.builtin.service:
      name: apache2
      state: started

  - name: Copy Ansible Logo
    ansible.builtin.copy:
      content: awx-spud.svg
      dest: "/var/www/html/awx-spud.svg"

  - name: Create test welcome page
    ansible.builtin.copy:
      content: "{{ lookup('template', 'index.html') }}"
      dest: "/var/www/html/index.html"

