---
- hosts: server01
  gather_facts: false
  tasks:
    - debug:
        msg: "{{ lookup('env', 'SN_HOST') }}"

    - name: Create ServiceNow ticket to resolve issue
      servicenow.itsm.incident:
        host: "{{ SN_HOST }}"
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
        short_description: "Unable to ping {{ inventory_hostname }}"
        impact: medium
        urgency: high

