---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create ServiceNow ticket to resolve issue
      servicenow.itsm.incident:
        short_description: "Unable to ping {{ inventory_hostname }}"
        impact: medium
        urgency: high

